### ISSUE TITLE
Pretty print with newlines and indentation

### ISSUE THREAD

**Issue by richard-viney** [gleam-lang/json#13]
Currently `json.to_string()` gives a string with no whitespace. This is sufficient much of the time, but it's also useful to be able to pretty print with newlines and indentations so it's more human-readable.

E.g.

```gleam
> to_pretty_string(array([1, 2, 3], of: int))
"[\n  1,\n  2,\n  3\n]"

> to_pretty_string(object([#("foo", string("bar")]))
"{\n  \"foo\": \"bar\"\n}"
```

**Comment by lpil** [comment]
Hello! This library won't support that as it'll impact the performance of the non-pretty printing path. It would be easy to implement as a new library though!
