### ISSUE TITLE
What is the proper way to decode a JSON array.

### ISSUE THREAD

**Issue by fwgreen** [gleam-lang/json#19]
I needed to decode a JSON array from database column.  My solution was to use regex to split the string into individual objects for decoding.  
```gleam
pub fn parse_json_array(
  array: String, 
  decoder: fn(String) -> Result(a, json.DecodeError)
) -> List(a) {
  let assert Ok(re) = regex.from_string("\\{[^}]*\\}")
  regex.scan(with: re, content: array)
  |> list.map(fn(match) { match.content })
  |> list.map(decoder) 
  |> result.values
}
```
It works, but is this the best way or does this library have something better that I'm not seeing?

**Comment by lpil** [comment]
Hello! Here's the function you want: https://hexdocs.pm/gleam_stdlib/gleam/dynamic.html#list
