### ISSUE TITLE
Add support to decode tuple

### ISSUE THREAD

**Issue by akiomik** [gleam-lang/json#9]
Thank you for the great language and libraries.

I would like to decode the following JSON:

```json
["1234", {"id": "5678", "created_at": 123}]
```

So I tried the following code, but an error occurred.

```gleam
import gleam/dynamic.{field, element}
import gleam/json.{decode}

pub type InnerData {
  InnerData(id: String, created_at: Int)
}

pub type OuterData {
  OuterData(label: String, data: InnerData)
}

let inner_data_decoder = dynamic.decode2(
  InnerData,
  field("id", dynamic.string),
  field("created_at", dynamic.int),
)

let outer_data_decoder = dynamic.decode2(
  OuterData,
  element(0, dynamic.string),
  element(1, inner_data_decoder),
)

decode("[\"1234\", {\"id\": \"5678\", \"created_at\": 123}]", outer_data_decoder)

// {error,
//   {unexpected_format,
//    [{decode_error,<<"Tuple">>,<<"List">>,[]},
//     {decode_error,<<"Tuple">>,<<"List">>,[]}]}}
```

This error indicates that the root JSON type is automatically treated as a list. This can be avoided by using `json.decode` and `dynamic.any`, but it is not smart.

It would be great if you could support tuples to make it easier to dacode to any custom type.

**Comment by lpil** [comment]
Check out the [`tuple2`](https://hexdocs.pm/gleam_stdlib/gleam/dynamic.html#tuple2) function in the dynamic module

**Comment by akiomik** [comment]
Thank you!
